title: Valkey
description: >-
  Multi-line PLACEHOLDER
baseurl: ""
url: ""

headings:
  blog: 'Blog'
  source: 'Source Code'
  authors: 'Authors'


# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate

defaults:
-
    scope:
      path: ""
      type: "posts"
    values:
      permalink: blog/:categories/:year/:month/:title/
- 
    scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
      permalink: /:collection/:name/
-
  scope:
    path: ""
    type: "releases"
  values:
    layout: "release"
    permalink: download/:collection/:name

collections:
  authors:
    output: true
  releases:
    output: true

paginate: 5
paginate_path: "/blog/page:num/"



# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - bower.json
  - package.json
  - .idea/
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - README.md