base_url = "https://valkey.io"

compile_sass = true

build_search_index = true

taxonomies = [
    { name = "Technical Blog Posts", feed = true}
]

[markdown]
highlight_code = true

# This is included to override any differences slugs and documentation source filenames
[extra.slug_source_exceptions]
"valkey-conf" = "valkey.conf"

[extra]
command_description_path = "../build-command-docs/"
command_json_path = "../build-command-json/"
doc_topic_path = "../build-topics/"

review_list = [
    "/docs/topics/license/",
    "/docs/topics/admin/",
    "/docs/topics/distlock/",
    "/docs/topics/eval-intro/",
    "/docs/topics/faq/",
    "/docs/topics/functions-intro/",
    "/docs/topics/hashes/",
    "/docs/topics/internals-eventlib/",
    "/docs/topics/internals-vm/",
    "/docs/topics/internals/",
    "/docs/topics/latency/",
    "/docs/topics/lua-api/",
    "/docs/topics/modules-blocking-ops/",
    "/docs/topics/modules-intro/",
    "/docs/topics/pipelining/",
    "/docs/topics/programmability/",
    "/docs/topics/protocol/",
    "/docs/topics/pubsub/",
    "/docs/topics/rdd/",
    "/docs/topics/replication/",
    "/docs/topics/security/",
    "/docs/topics/sentinel-clients/",
    "/docs/topics/sentinel/",
    "/docs/topics/transactions/",
    "/docs/topics/cluster-spec/",
    "/docs/topics/history/"
]

publish_hold = [
    "/docs/topics/protocol/",
    "/docs/topics/license/",
    "/docs/topics/internals-eventlib/",
    "/docs/topics/internals-vm/",
    "/docs/topics/internals/",
    "/docs/topics/protocol/",
    "/docs/topics/rdd/"
]